//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micraft_Task
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblOrder
    {
        public int OrderId { get; set; }
        [DisplayName("Order Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> OrderDate { get; set; }

        [DisplayName("Customer")]
        public Nullable<int> CustomerId { get; set; }
        [DisplayName("Total Quantity")]
        public Nullable<int> TotalQty { get; set; }
        [DisplayName("Total Amount")]
        public Nullable<decimal> TotalAmount { get; set; }
        
        public virtual Customer Customer { get; set; }
    }
}
